export enum NamingConvention {
  PASCAL_CASE = "PASCAL_CASE",
  CAMEL_CASE = "CAMEL_CASE",
  SNAKE_CASE = "SNAKE_CASE",
  SCREAMING_SNAKE_CASE = "SCREAMING_SNAKE_CASE",
  KEBAB_CASE = "KEBAB_CASE",
}
